from telegram import *
from telegram.ext import *
import secrets
import re

admechQuotes = [
    ("Admonitions Mechanae 3:16", "Seek not the words of the xenos, lest they infect us with blasphemy\."), 
    ("Aetheric Manuscripts Appendix 71", "Without a Standard Model, there is naught but madness and Chaos among the stars\."), 
    ("Amalanthians 9\.41", "Thus does the Enemy seek to crush our spirit, for our souls are our most potent weapon\."), 
    ("Amarinthine Admonitions", "If it resembles a heretic, if it speaks like a heretic, and if it be redolent to the nose, as if like a heretic, then a heretic it will be\!"), 
    ("Amalathian Commentaries Chapter 94", "We fight the foe’s battle for him, when we take his words into our hearts\."), 
    ("Amaranthine Verses 78\.12", "No task that is easy is ever worthwhile\."), 
    ("Antonine Musings 901\.45", "Failure is unique among sin, in that we can turn it into a virtue when it drives us to succeed\."), 
    ("Aphorisms 7\.1", "There are horrors in this galaxy that only faith and steel can overcome, and that we should be grateful we shall never fully understand\."), 
    ("Aphorisms 7\.31", "Grant a coward the excuse to retreat from the battlefield and he will never fight again\."), 
    ("Aphorisms 56", "Look not upon the alien, for the alien looks back\."), 
    ("Aphorisms 94\.13", "The Enemy rushes to action, when our ministrations cause him fear"), 
    ("Aphorisms 97", "If it is worth doing, it is worth doing to completion\."), 
    ("Aphorisms of the Logic\-Saints 7\.91", "In the presence of the xenos lies the invisible miasma of corruption\."), 
    ("Appendix Heuristica 73\.90", "And we shall cast them down, that corrupt by their presence;\nWe shall break the teeth of the xenos that would swallow us whole\."), 
    ("Armageddon Verses 13\.90", "They need not rend us with their blades\. They have but to make us witness them, and thereby can we fall\."), 
    ("Avelornians 5\.91", "Fragile indeed are the tools of the righteous\."), 
    ("Cannot unless you Canticle v\.34", "The only will of the Machine Spirit is that of the Omnissian technologies,\nfor the Xenos will deceive you and tempt you, but you will not falter, for you are a Priest\."), 
    ("Canticles Borealis 6\.15", "Inefficiency is a slope whereupon one slides ever downwards, by degrees, until one reaches the nadir unknowing\."), 
    ("Canticles Flamminia 713", "When we muse on the works of the enemy, we invite him into our minds\."), 
    ("Canticles Logica 6\.41", "Where corruption remains, men will fall\."), 
    ("Canticles of Gethsemenoth Line 87", "Let the weaker in mind follow the words of the strong\!"), 
    ("Canticles of Mars 79\.12", "Rejoice\. Give thanks\. For we are but one step now from triumph\."), 
    ("Castigations 17\.4", "Thus are the wages of those who delve too deep\."), 
    ("Catechism of the Autoculus of Mars \- excerpt", "Toll the Great Bell Once\!\nPull the Lever forward to engage the\nPiston and Pumpg\.\.\.\nToll the Great Bell Twice\!\nWith push of Button fire the Engine\nAnd spark Turbine into life\.\.\.\nToll the Great Bell Thrice\!\nSing Praise to the\nGod of All Machines"), 
    ("Chant for the prevention of malfunction", "May your weapon be guarded against malfunction,\nAs your soul is guarded from impurity\.\nThe Machine God watches over you\.\nUnleash the weapons of war\.\nUnleash the Deathdealer\."), 
    ("Codex Fulminatus 83\.12", "Show caution and scorn in all things\."), 
    ("Cognis Amalathian 5\.89", "A Tech\-Priest eschews the illogicality of fear, the unbalanced equation of doubt, the broken circuit of failure\."), 
    ("Collected Logic\-Psalms 31\.3", "And lo, shall Your holy steel be as armour around our souls, and shall Your wisdom guide our hands\.\nNo spear nor barb of the enemy shall trouble our flesh of iron\. Let the will of Mars be done\!"), 
    ("Colloquialisms Minor Chapter 51", "It’s not work if you enjoy it\."), 
    ("Colloquialisms of Metalica Chapter 52", "Enough fire in the right place can solve any problem\."), 
    ("Conceptua Comprehensis Verse 329", "Blessed is he who, in death, does his duty\."), 
    ("Confessions of Logic\-Saint Levistian", "There can be no forgiveness now\. No penitence that will satisfy my sin\."), 
    ("Contemplations Hagiographica", "Death itself is scarcely an excuse for the sin of duty undone\."), 
    ("Epigrams of Saint Eukelsis 3\.89", "Protect the shield of the mind, and the body will be shielded thereby\."), 
    ("Epigraphs Macrologica Psalm 105", "Wheresoever the blasphemer writes, obliterate\."), 
    ("Eukelkisians 60\.24", "Men fuelled by the righteousness of their purpose can achieve what armies cannot\."), 
    ("Exaltations 49", "The Lord of Mars is with us in the dark, even if thou knowest it not\."), 
    ("Exhortationes Principiis Titannorum, Divisio Militaris", "We are all but a weapon in the right hand of the Emperor\."), 
    ("Ferro\-Dictates 53\.12", "Not all data should be acquired\."), 
    ("Formulae Technologia Verses 4\-27", "Cursed be silence, when the Omnissiah’s word should ring out\."), 
    ("Gathalamorians 6\.13", "And endeavour is its own reward\."), 
    ("Gathalamorians 9\.41", "When the final analysis is fully calculated, all equations balance against righteous annihilation\."), 
    ("Gathalamorians 45\.7", "Above bullets, above blades, care for your soul above all\."), 
    ("Gathalamorians 60\.41", "He who prosecutes the alien with zeal, is the ally of Mankind\."), 
    ("Gathalamorians 71\.6", "By Flame Shall The Unclean Be Made Clean, By Fire Shall The Unholy Be Made Holy\."), 
    ("Gathalamorians 71\.30", "Even in the deepest darkness, give devotion to the Omnissiah, for there He is needed the most\."), 
    ("Gathalamorians 94\.3", "Be thou wary of the works of the alien, for their presence is poison and their every word deceit\."), 
    ("Gathalamorians 97\.14", "He who aids the blasphemer, even through ignorance, has the blood of the faithful upon his hands\!"), 
    ("Gathalamorians 714\.5", "Obliterate his words, cut out his tongue, put to fire all wrought by his hand, and the heretic shall cease to exist\."), 
    ("Hagiographies of Saint Regulavis 91\.12", "Purification is the prelude to annihilation\."), 
    ("Hagiography of Thor 14\.91", "He who sows doubt is as blameful as he who sheds blood\."), 
    ("Helfirian Recollections Chapter 571", "When the enemy begs for destruction, do not let him go hungry\."), 
    ("Hymn of Reforging", "Thus do we invoke the Machine God\.\nThus do we make whole that which was sundered\."), 
    ("Jovian Commentaries Chapter 59", "The tree of heresy persists were its roots be not torn up\."), 
    ("Jovian Ministrations 61\.90", "When the heretic is silenced, it is as if his weapons and tools are stripped from him, he is left impotent and weak\."), 
    ("Jovian Tutelage 56\.41", "It is a rare man whose faith survives the failings of his superiors\."), 
    ("Kalemnan Orations 5\.25", "The sweet incense of faith conquers the toxic stench of corruption\."), 
    ("Keraptic Inscriptions Chapter 15", "Wheresoever the sacred man tread, led it be made pure, or say he is not sacred\."), 
    ("Kryptmann Verses 11\-13", "Ware the script of the enemy\! For writ into its lies are the seeds of corruption\."), 
    ("Levistians 7\.14", "Bleak be the prospects, when the black wind of heresy blows\."), 
    ("Levistians 9\.22", "Knowledge will ever be a blessing and a curse\."), 
    ("Life of Archmagos Borasis Appendix 9", "Our only objective should be death to the alien and all his works\. All else is deviance from the Omnissiah Creed\."), 
    ("Life of Fabricator General Kane 56\.90", "Annihilation\. Not exile, submission or subjugation\. For the xenos, only annihilation\."), 
    ("Life of Macharius 23\.19", "Then into the teeth of the enemy we shall stride\."), 
    ("Life of Saint Dacianus Chapter 60", "Give thanks only that the enemy has fallen\.\nCare not for his motives, nor for the promise of his teachings\.\nDefine him solely by his death, and the gains Mankind makes thereby\."), 
    ("Life of Saint Hermeticus 5\.23", "Faith is light, and where it burns, there is no night\."), 
    ("Linguis Fulminatus Chapter 7", "Improvisation is rarely to be welcomed, and then only when the Omnissiah’s will demands it\."), 
    ("Lives of Gyarados 73\.60", "If it has not a head to sever, cut out the heart\."), 
    ("Logistae Septimus 21\.4", "The circuits are complete\. The engine of fate is primed\. One turn of the cog remains, and the grand machine shall fulfil its purpose\."), 
    ("Lord of the Engines, 16th Tome, Verse 2001", "And when at last he came upon the vehicle, he perceived the distress of the engine therein and forthwith struck the rune and it was good\. Thereupon the engine ignited and was filled with strength\.\.\."), 
    ("Macharians 16\.4", "Watch your brother, for his sin of heresy is thy sin of tolerance\."), 
    ("Macharian Axioms Line 918", "The wilful child is as the maddened steed: when it is let off its leash, it is lost\."), 
    ("Macharian Commentaries Chapter 71", "As we purify the ground beneath their feet, they shall find no shelter\!"), 
    ("Macharian Commentaries 73\.5", "Seek profane knowledge, and find profane fates\."), 
    ("Macharian Duologues Chapter 61", "Let the foe blunt their blades against our resolve\. They will be ash and memories soon enough\."), 
    ("Macharian Notions Chapter 4113", "Better safe and ignorant, than rueing the means of our downfall\."), 
    ("Malchadorian Insights 17\.4", "First comes knowledge of destruction, then its execution\."), 
    ("Maxims Metalica 76\.12", "From such small heresies are great apostasies made\."), 
    ("Maxims of Amalanth 5\.12", "Beware the deviance of thine own tools, for the Enemy finds his entrance thereby\."), 
    ("Meditations Logicae Verse 619", "How dim the sacred light burns when the unholy darkness loometh all about\."), 
    ("Meditations on the Superlogicae Verse 971", "When the corruption of the unholy becomes manifest to our senses, a far greater corruption lies unseen\."), 
    ("Memoirs of Saint Hestios 5\.25", "Blessed is that life that, in its ending, forgives a lifetime of sin\."), 
    ("Mensis Hagiographica Appendix 91", "Thus does Mankind fail\. Not in knowing betrayal, but in the silent sin of duty neglected\."), 
    ("Neodogmatics 71\.90", "If His Will be done, let it be done quickly\."), 
    ("Observations on the Tech\-Cosmos Verse 68", "We are derelict in our duty whenever we allow corruption to plague the minds of good men\."), 
    ("Opus Fulminata", "The Omnissiah demands the stain of the xenos be deleted\. Where it remains, the Omnissiah rages\."), 
    ("Principae Logica 22\.4", "Let His word be exalted to the eleventh degree\."), 
    ("Psalms Hermeticus 46", "The xenos must be purged, for the stars are humanity’s birthright\."), 
    ("Quaestos Mechanicor 5\.21", "From the mouths of heretics emit naught but foul vapours\. Cut out the tongue and be clean\."), 
    ("Recollections of Inquisitor Brand Chapter 87", "Of all creations most foul I beheld the Lord of All and knew that I was dead\."), 
    ("Recollections of Saint Hesperis Volume 17", "I beheld the babel of the enemy’s tongues, and I was overwhelmed by a wall of heresy\."), 
    ("Revelations of Titan 18\.12", "The enemy shall take what we give him, and reap a harvest behind our backs besides, until whole worlds are lost to our sight\."), 
    ("Runic Mechanics \- An Introduction", "The beast of metal endures longer than the flesh of men\. Those that tend the beasts of metal must labour long to learn its ways, for a single beast must suffer the mastership of many men until ready to shed its vorpal coils\. Those that seek apprenticeship must attended closely to the runes of mobilisation, the rites of maintenance, and the words\-of\-power that describe the parts of a beast\. Nor must they neglect the tutelage of the Adeptus Prefects, nor the casting of the proper roboscopes\."), 
    ("Runic Spaceflight \- An Introduction; Naval Flight Manual W110E", "Strike the first rune upon the engine's casing employing the chosen wrench\. Its tip should be anointed with the oil of engineering using the proper incantation when the auspices are correct\. Strike the second rune upon the engine's casing employing the arc\-tip of the power\-driver\. If the second rune is not good, a third rune may be struck in like manner to the first\. This is done according to the true ritual laid down by Scotti the Enginseer\. A libation should be offered\. If this sequence is properly observed the engines may be brought to full activation by depressing the large panel marked \"ON\"\."), 
    ("Saturnine Verses 81\.4", "The loose tongues of our soldiers are as guns in the hands of our enemies\."), 
    ("Sayings of Archmagos Cortiko Verse 58", "Prayer has power, but I cannot deny fire does, too\."), 
    ("Sayings of the Archmagi Appendix 4", "Such sweet music is the chatter of binary, that has no tongue to lie\."), 
    ("Sayings of the Princeps 65\.4", "When thou desirest to discourse purely, use binary\."), 
    ("Scripture of the Taloned Cog v\.09 p\.3", "Wary of those that wonder\."), 
    ("Selucian Aphorisms Verse 539", "Sometimes the weak limb must be amputated before the whole body withers\."), 
    ("Text of the Oiled Cog v\.12", "One can verge from the standard form, but one must always retain their humanity, or be lost to the Men of Iron and their ways\."), 
    ("The Book of Five Runes", "When uttering the incantation, mark well that the rod is upon and not within the intake\. The second incantation should not be uttered until all the fumes have come forth, then the way shall be clear for the sacred words to penetrate unto the heart of the engine\. If the mounting be hot say the third rune, if it be cold the fourth rune is more appropriate\. For then the wrath of the engine will be aroused\.\.\."), 
    ("The Life of Fabricator General Heuristicus VII", "An opportunity wasted is a sin preserved\."), 
    ("The Life of Uriah Jacobus 8\.31", "When the enemy offers open battle, take it, and make it his final mistake\."), 
    ("The Litany of Ignition", "The soul of the Machine God surrounds thee\.\nThe power of the Machine God invests thee\.\nThe hate of the Machine God drives thee\.\nThe Machine God endows thee with life\.\nLive\!"), 
    ("The Lives of the Logic\-Saints Psalm 61", "Even In Death, Our Duty Is Not Complete\."), 
    ("The Prima Incubatorta, rite of Titan awakening", "The will of the Emperor is done\.\nAs the blood of the slain is laid upon you so may you lay the enemy’s blood at the feet of the Emperor\.\nLay blood at the Emperor's feet\.\nAs the rune of protection is inscribed upon you so may the litanies of protection ward your soul\.\nMay your soul be guarded from impurity\.\nAs the warriors within you guide your weapons, may you in your turn, guide their lives\.\nStand true against the trials of war\."), 
    ("Themiscyran Manuscripts Verse 619", "What the enemy built, let it be made asunder, for to us it will be as a house of sand and knives\."), 
    ("Verses Fulminatus 59\.31", "The broken in body can blame the bullet or the sword, but the broken in mind have all creation to curse\."), 
    ("Verses Macrologica 17\.4 ", "The only logical response to the presence of the xenos, is hatred\."), 
]

async def vox(update: Update, context: ContextTypes.DEFAULT_TYPE):
    index = secrets.choice(range(0, 109))
    quote = '_' + admechQuotes[index][1] + '_'
    frm = '*' + admechQuotes[index][0] + '*'
    await context.bot.send_message(chat_id=update.effective_chat.id, text=quote + "\n" + frm, parse_mode='MarkdownV2')