male = [
    "Agustín",
    "Alonso",
    "Alvaro",
    "Andrés",
    "Antón",
    "Antonio",
    "Baltasar",
    "Barros",
    "Bartolomé",
    "Bastía",
    "Bautista",
    "Benito",
    "Bernardino",
    "Blas",
    "Carlos",
    "Cosme",
    "Cristóbal",
    "Diego",
    "Domingo",
    "Esteban",
    "Eyague",
    "Felipe",
    "Francisco",
    "Frutos",
    "Gabriel",
    "Garci",
    "Gaspar",
    "Gines",
    "Giraldo",
    "Gonzalo",
    "Gregorio",
    "Guillen",
    "Hector",
    "Hernán",
    "Hernando",
    "Jaime",
    "Jerónimo",
    "Jorge",
    "Jose",
    "Juan",
    "Lope",
    "Lorenzo",
    "Lucas",
    "Luis",
    "Manuel",
    "Marcos",
    "Martín",
    "Mateo",
    "Matias",
    "Melchor",
    "Mergildo",
    "Miguel",
    "Nicolas",
    "Pablo",
    "Pascual",
    "Pedro",
    "Rodrigo",
    "Salvador",
    "Sancho",
    "Santiago",
    "Sebastian",
    "Simón",
    "Tomás",
    "Tomé",
    "Truylos",
]

female = [
    "Agueda", 
    "Ana", 
    "Andrea", 
    "Angela", 
    "Antona", 
    "Antonia", 
    "Beatriz", 
    "Barbola", 
    "Catalina", 
    "Clara", 
    "Constanza", 
    "Costanza", 
    "Cristina", 
    "Damiana", 
    "Elvira", 
    "Floriana", 
    "Francisca", 
    "Inés", 
    "Isabel", 
    "Jerónima", 
    "Juliana", 
    "Juana", 
    "Leonor", 
    "Lucia", 
    "Luisa", 
    "Magdalena", 
    "Margarita", 
    "María", 
    "Mariana", 
    "Marina", 
    "Mayor", 
    "Melchora", 
    "Mencía", 
    "Olall", 
    "Quiteria", 
    "Sancha", 
    "Susana", 
    "Teresa", 
    "Ursula", 
    "Violante", 
]

byname = [
    "del Aguila",
    "de Aguilar",
    "de Ahumada",
    "Aloy",
    "de Alvarado",
    "de Anania",
    "de Andrada",
    "de Anero",
    "de Aracena",
    "de Aranda",
    "de Araújo",
    "Arias",
    "de Avila",
    "de Baena",
    "de Baeza",
    "de Barrionuevo",
    "Barroso/Barrosa",
    "Blaque",
    "Blas",
    "de Burgos",
    "Caballero",
    "Cabezas",
    "de Cáceres",
    "de Calatrava",
    "del Canto",
    "Cardero",
    "Carrillo",
    "de Carrión",
    "de Castilla",
    "del Castillo",
    "de Castro",
    "Cerrada",
    "de Céspedes",
    "de la Corona",
    "de la Corredera",
    "Cortés",
    "de la Cruz",
    "de la Cueva",
    "Chico",
    "Díaz",
    "Díez",
    "Donoso",
    "Ejarque",
    "de Eslava",
    "de Espinosa",
    "Farfán",
    "Fillado",
    "de Foronda",
    "de la Fuente",
    "de Fuentes",
    "Galán",
    "García",
    "Gómez",
    "González",
    "Gutiérrez",
    "Hernández",
    "de Herrera",
    "del Hoyo",
    "de Jerez",
    "Jiménez",
    "Juárez",
    "de León",
    "de Lepe",
    "Lomelin",
    "López",
    "Luengo",
    "de Luján",
    "Macías",
    "de Marchena",
    "Marita",
    "Marqués",
    "Martín",
    "Martínez",
    "de Medina",
    "Méndez",
    "de Mendoza",
    "de Molina",
    "Monsalve",
    "Montañés",
    "de Montoya",
    "de Moraza",
    "Moreno",
    "Muñoz",
    "de Navarrete",
    "Nelleda",
    "Nuñez",
    "de Olivares",
    "de Onís",
    "Ortiz",
    "de Ovando",
    "de Ozayta",
    "de Palategui",
    "de Palencia",
    "de \(la\) Palma",
    "de Paz",
    "Peinado",
    "Perdigon",
    "Pérez",
    "Pinto",
    "Pizarro",
    "Pletes",
    "de Porras",
    "de Porres",
    "Quijada",
    "Ramírez",
    "Ramos",
    "de Ribera",
    "Riquel",
    "de Rivera",
    "de Robledo",
    "Rodríguez",
    "la Roja/el Rojo",
    "de Rojas",
    "Ruiz",
    "de Salazar",
    "de Samaniega",
    "de San Martín",
    "de San Millán",
    "Sánchez",
    "de Santa Cruz",
    "Sanz",
    "Sañudo",
    "de Saucedo",
    "de Segovia",
    "Solucio",
    "de Soto",
    "Suárez",
    "Suero",
    "de Tapia",
    "de Tejeda",
    "de la Torre",
    "de Torres",
    "de Trillo",
    "de Trujillo",
    "Vaca",
    "de Vadillo",
    "de Valderrama",
    "de Valencia",
    "del Valle",
    "Vázquez",
    "de Villanueva",
    "de Villarreal",
    "Vizcaína",
    "Yañez",
    "de Zárate",
]